import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { paths } from '../config.js';
import { logger } from '../logger.js';

/** Folder artwork names, in priority order (PRD §36). */
const FOLDER_ARTWORK = ['cover.jpg', 'cover.jpeg', 'cover.png', 'folder.jpg', 'folder.png', 'album.jpg', 'albumart.jpg'];

const EXTENSION_BY_MIME = {
  'image/jpeg': '.jpg',
  'image/jpg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
  'image/gif': '.gif',
};

export async function findFolderArtwork(directory) {
  for (const name of FOLDER_ARTWORK) {
    const candidate = path.join(directory, name);
    try {
      const stat = await fs.stat(candidate);
      if (stat.isFile()) return candidate;
    } catch {
      /* not present */
    }
  }
  return null;
}

/**
 * Persists cover art into the cache directory, keyed by album id.
 * Returns `{ filename, hash }`, or null when nothing changed / nothing found.
 * `previousHash` short-circuits identical artwork so rescans stay cheap.
 */
export async function cacheArtwork(albumId, { buffer, format, previousHash }) {
  if (!buffer?.length) return null;

  const hash = crypto.createHash('sha1').update(buffer).digest('hex');
  if (previousHash && previousHash === hash) return null;

  const extension = EXTENSION_BY_MIME[String(format).toLowerCase()] || '.jpg';
  const filename = `${albumId}${extension}`;

  // Remove any stale files for this album with a different extension.
  for (const ext of new Set(Object.values(EXTENSION_BY_MIME))) {
    if (ext === extension) continue;
    await fs.rm(path.join(paths.artworkCache, `${albumId}${ext}`), { force: true });
  }

  await fs.writeFile(path.join(paths.artworkCache, filename), buffer);
  logger.debug('artwork cached', { albumId, filename, bytes: buffer.length });
  return { filename, hash };
}

export async function artworkFilePath(filename) {
  // Artwork filenames are generated by us, but re-validate anyway.
  const safe = path.basename(String(filename || ''));
  if (!safe) return null;
  const full = path.join(paths.artworkCache, safe);
  try {
    const stat = await fs.stat(full);
    return stat.isFile() ? full : null;
  } catch {
    return null;
  }
}

export async function readFolderArtwork(filePath) {
  const buffer = await fs.readFile(filePath);
  const extension = path.extname(filePath).toLowerCase();
  const format =
    extension === '.png' ? 'image/png' : extension === '.webp' ? 'image/webp' : extension === '.gif' ? 'image/gif' : 'image/jpeg';
  return { buffer, format };
}
